### ISSUE TITLE
[Feat] Tuist로 모듈 분리하기

### ISSUE THREAD

**Issue by 0inn** [sopt-makers/SOPT-iOS#121]
## 📌  Issue
Tuist로 모듈 분리합니다.

## 📝  To-do

- [ ] 구조 잡기
- [ ] 모듈 분리

**Comment by L-j-h-c** [comment]
@0inn @elesahich @lsj8706 @devxsby 

Feature 모듈은
- Splash
- Auth 
- Stamp
- Main(소스 비워두기) 
- Setting(소스 비워두기)

이렇게 나누면 될 것 같은데 어떻게 생각하시나요?

미리 틀을 잡아놓고 운영 / 플그 / 공홈 등 새로운 Feature는 그때그때 추가하는 식으로??

**Comment by devxsby** [comment]
@L-j-h-c 좋은 것 같아용~ 근데 메인 피처가 뭔가요?

**Comment by devxsby** [comment]
@L-j-h-c 좋아용 !
그런데 운영 서비스팀에서 출석, 공지 기능 피처가 있고 바로 디벨롭 할 것 같아서 이건 지금 넣어줘도 될 것 같은데 어떻게 생각하시나요!?
그리고 메인 피처는 어떤게 들어갈 지 잘 모르겠어요.. 🤔
슈퍼앱스럽게 리디자인 한다면 이 Main이 제가 생각하는 피처들의 더 큰 상위 계층인 첫 진입뷰가 되는건가용..?

**Comment by elesahich** [comment]
저도 큰 이견은 없어요~!
사소한것 으로는 : Auth는 로그인을 담당하는 뷰를 보여주는 것일까요? 10초 정도 생각해 보았을 때는 보안이 필요한 모든 곳에서 사용해야겠다고 생각했거든요. 만약 뷰가 있거나 있을 예정이라면 SignIn이 어떨까 합니다. 의견 편히 주세요~ 😀

**Comment by L-j-h-c** [comment]
> @L-j-h-c 좋아용 ! 그런데 운영 서비스팀에서 출석, 공지 기능 피처가 있고 바로 디벨롭 할 것 같아서 이건 지금 넣어줘도 될 것 같은데 어떻게 생각하시나요!? 그리고 메인 피처는 어떤게 들어갈 지 잘 모르겠어요.. 🤔 슈퍼앱스럽게 리디자인 한다면 이 Main이 제가 생각하는 피처들의 더 큰 상위 계층인 첫 진입뷰가 되는건가용..?

Main은 생각하신 것처럼 첫 진입 뷰로 생각했고, 운영 Feature도 미리 넣어두는 것에 동의합니다!!

> 사소한것 으로는 : Auth는 로그인을 담당하는 뷰를 보여주는 것일까요? 10초 정도 생각해 보았을 때는 보안이 필요한 모든 곳에서 사용해야겠다고 생각했거든요. 만약 뷰가 있거나 있을 예정이라면 SignIn이 어떨까 합니다. 의견 편히 주세요~ 😀

Auth는 로그인과 회원가입 뷰를 보여주는 것으로 생각했어요! Auth라는 네이밍을 SignIn으로 조금 더 구체적이게 바꾸는 방향으로 생각하셨을까요?

**Comment by 0inn** [comment]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/74968390/224684079-1c845cb3-512b-4553-99a7-2445cbf51c1f.png">

- Splash :  Splash
- Auth : SignIn, SignUp
- Stamp : ListDetail, MissionCompleted, MissionList, Ranking
- Main(소스 비워두기)
- Setting : Setting
- Attendance(소스 비워두기)
- Notice(소스 비워두기)

**논의 사항**
1. Alert랑 Onboarding은 어디에 넣는게 좋다고 생각하시나요 ? 
혹은 새로 피처를 만들면 어떤 네이밍으로 할까요 . . ? (ex. Base)
2. 현재 피그마를 보면 출첵이랑 공지가 하나의 뷰로 만들어질 가능성도 있어 보이는데 그럼에도 피처를 나누는 게 나을까요 ?

**Comment by L-j-h-c** [comment]
@0inn 
개인적으로 생각했던 Feature를 나누는 기준은 Scene 끼리 얼마나 연관되어 있는가 였는데요! 예를 들어 SignIn이나 SignUp같은 경우 밀접한 관련이 있으니 하나의 피쳐로 보는 식이죠. 정도의 차이라고 생각해서 Onboarding도 독립된 피쳐로 분리할 수 있다고 생각해요!

Alert는 모든 Feature에서 쓰이고 있으니 Design System 쪽에 넣어도 되지 않을까 하는 생각이 듭니다아... 변경이 적을 것 같기에 괜찮지 않을까요?

출첵과 공지가 하나의 뷰로 만들어진다는 것이 메인 뷰에서 진입하면 하나의 뷰만 존재한다는 말씀이실까요??
모듈을 나눴을 때와 나누지 않았을 때 개발자 경험, 유지보수 비용 등을 종합적으로 판단해서 결정하시면 좋을 것 같아요!
그리고 조금 다른 이야기일 수 있지만, 하나의 뷰라도 너무 복잡도가 높다면 여러 Features로 나눌 수 있다는 생각입니다.

**Comment by lsj8706** [comment]
제 생각에도 온보딩은 별도의 Feature로 구성할 수 있을 것 같습니다.
Alert 경우에는 생각을 조금 해볼만한 점으로 현재 Alert는 솝탬프를 위해 디자인되어 있습니다. 따라서 추후에 혹시나 솝트 앱 전반적인 디자인 시스템과는 조금 동떨어진 UI가 될수도 있습니다. 아마도 새로운 팝업 UI 디자인이 나올수도 있겠다는 추측입니다. 그렇게 된다면 현재 존재하는 Alert는 Soptamp 모듈에서만 사용될 수도 있는데 그럼에도 일단은 Design System에 넣는게 맞을까요..? 물론 새로운 Alert UI가 나올때까지는 시간이 꽤 걸릴 것 같아서 사실 지금은 크게 상관은 없을 거 같기는 합니다.

**Comment by L-j-h-c** [comment]
그렇네요 alert는 soptamp에 합쳐도 될 것 같슴당...! alert가 조금 더 일반적이었던 것으로 착각했네요~~ 😃😃

**Comment by 0inn** [comment]
네 ! 
그럼 모듈은 아래와 같이 구성하겠습니다 ~

- Splash : Splash
- Onboarding: Onboarding
- Auth : SignIn, SignUp
- Stamp : ListDetail, MissionCompleted, MissionList, Ranking, Alert
- Main(소스 비워두기)
- Setting : Setting
- Attendance(소스 비워두기)
- Notice(소스 비워두기)
