### ISSUE TITLE
[Chore] 로그인, 팝업, 알림 뷰 보라색 제거

### ISSUE THREAD

**Issue by lsj8706** [sopt-makers/SOPT-iOS#269]
## 📌  Issue

로그인, 팝업, 알림 뷰 보라색 제거

## 📝  To-do

- [ ] 로그인 뷰
- [ ] 팝업 뷰
- [ ] 알림 뷰

**Comment by devxsby** [comment]
+ 탈퇴하기 뷰 버튼, 한마디 편집, 닉네임 변경 뷰도 발견했어요..!

**Comment by lsj8706** [comment]
> * 탈퇴하기 뷰 버튼, 한마디 편집, 닉네임 변경 뷰도 발견했어요..!

이쪽 뷰는 승호형 담당인데 사실 내가 메인 뷰 작업하다보니까 다 공통 Component로 묶여 있어서 설정뷰쪽도 같이 보라색 제거된다!
