### ISSUE TITLE
How to run fastlane

### ISSUE THREAD

**Issue by toanbv-fabbi** [sopt-makers/SOPT-iOS#413]
I run command `fastlane start_project` but received issues
![Screenshot 2024-10-18 at 15 06 35](https://github.com/user-attachments/assets/b8085f56-e39f-4d7e-867c-babd84f22e0b)
please help me

**Comment by meltsplit** [comment]
I’m not fully confident in my understanding of the Fastlane code, so it’s difficult to provide a definitive answer.

**Cause of the Issue**

We are managing private files in the SOPT-iOS-Private repository. In the start_project lane of Fastlane, there is a process that accesses this repository to retrieve private files. You can find this logic in the SOPT-iOS/SOPT-iOS/Makefile.

**Possible Solutions**

There seem to be two ways to resolve this issue:

1. Remove the code in the Makefile that accesses this repository, then run tuist edit and modify the related code(SOPT-iOS/SOPT-iOS/Plugins/ConfigPlugin/ProjectDescriptionHelpers/Configurations.swift)

2. Change the baseURL in the Makefile to a repository URL that you have access to. Then, add the xcconfig files in the specified path according to the structure defined in the Makefile.

I apologize for not being able to provide a more definitive answer.
